### ISSUE TITLE
The name of your file already has the answer

### ISSUE THREAD

**Issue by fabianmoronzirfas** [edgalindo/01_designAword#1]
😭 but but I wanted to guess

**Comment by edgalindo** [comment]
I know but the file is anyway wrong, then we must draw only one shape for the belonging  adjective.... I just leave it here as a exercise for myself;).
I'll start again trying with one shape on the canvas.

**Comment by fabianmoronzirfas** [comment]
We could discuss if one shape means only "one" shape or only "one type of shape" 😉
